### PR TITLE
Fix support for custom filenames in start

### PR DESCRIPTION
**Pull request by swanijam**
Signed-off-by: James Swanick swanijam@gmail.com

### CODE REVIEW

**Comment by bruth** [comment]
I don't think this is needed because the script controls the filename and the output.

**Comment by swanijam** [comment]
It is needed, because it controls the filename and output, but uses the default intermediate file (metadata.json) as an argument in the following commands. If the input file is not named metadata, it still tries to find metadata.json.

**Comment by bruth** [comment]
So clarify, this line outputs a JSON file named after the input file?

``` bash
python bin/manage.py redcap json /input/$METADATA_FILE
```

**Comment by swanijam** [comment]
Yes, it does. metadata.csv is converted to metadata.json, metadata.json is used to create models.py, and then it used again with data.csv to create fixtures.json. fixtures and models are then used to describe the harvest data.

if metadata.csv file is named something else, say 'meta_data.csv', then the resulting json is called 
'meta_data.csv'

**Comment by bruth** [comment]
Got it.

**Pull request merged**
